### ISSUE TITLE
[Bug] Link field change results in failing schema updates

### ISSUE THREAD

**Issue by FLeudts** [derhansen/sf_event_mgt#1028]
### Extension version
6.2.3

### Short problem description
typo3cms database:updateschema fails with the change in #1007 because a standard null value is removed

### Steps to reproduce
1. Have events with no links in the DB
2. run typo3cms database:updateschema

### Expected behaviour
database:updateschema is should update the database sucessfully

### Server configuration
**TYPO3 version:**
v11.5.12
**PHP version:**
8.1.7

**Comment by derhansen** [comment]
How did you get `null` values into the `link` field? TYPO3 will AFAIK transform empty field values for TCA input fields of type `inputLink` with `'eval' => 'trim'` to an empty string. However, it seems at some point `null` values were saved to the field (at least in an old v7 test website locally), so the bug is valid. 

So the field has to be changed to: `link varchar(2048) DEFAULT '' NULL,`

**Comment by derhansen** [comment]
Changed the field to be nullable, so nobody else with `null` values in that field will run into unexpected problems.
