### ISSUE TITLE
No speaking urls in the sitemap - the speaking urls are displayed correctly in the browser

### ISSUE THREAD

**Issue by steff2000** [derhansen/sf_event_mgt#1051]
### Extension version
6.2.3

### Short problem description
I managed speaking urls for our events by configuring 'routeEnhancers' but in sitemap there are no speaking urls
Here an example from sitemap:
http://XXXXX.de/event?tx_sfeventmgt_pievent%5Baction%5D=detail&tx_sfeventmgt_pievent%5Bcontroller%5D=Event&tx_sfeventmgt_pievent%5Bevent%5D=1221&cHash=c329ff4f1a42599fe64e4bd1eb8d098a

I use the sitemap generation provided by Typo3 out of the box
Is there a config step that I missed?

### Steps to reproduce
configure speaking URLs for extension, then call XXXXXX.de/sitemap.xml

### Expected behaviour
speaking urls also in sitemap

### Actual behaviour
no speaking urls in sitemap

### Server configuration
**TYPO3 version:** 11.5.18

**PHP version:** 7.4.x

**Comment by derhansen** [comment]
You must also configure the sitemap to support extension records as described in the TYPO3 documentation (https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Seo/XmlSitemap.html#for-records).

For ext:sf_event_mgt this is most likely something like the following snippet:

```
      events {
        provider = TYPO3\CMS\Seo\XmlSitemap\RecordsXmlSitemapDataProvider
        config {
          table = tx_sfeventmgt_domain_model_event
          sortField = tstamp
          lastModifiedField = tstamp
          pid = <YOUR-STORAGE-PID>
          recursive = 0
          url {
            pageId = <YOUR-DETAIL-PID>
            fieldToParameterMap {
              uid = tx_sfeventmgt_pieventdetail[event]
            }
            additionalGetParameters {
              tx_sfeventmgt_pieventdetail.controller = Event
              tx_sfeventmgt_pieventdetail.action = detail
            }
            useCacheHash = 1
          }
        }
      }
```

Make sure to replace `<YOUR-STORAGE-PID>` and `<YOUR-DETAIL-PID>` with the page UIDs that match your setup.

I'm closing this ticket now, since this is not issue in the extension but a general TYPO3 configuration issue.
