### ISSUE TITLE
Map of location empty

### ISSUE THREAD

**Issue by erichenn** [derhansen/sf_event_mgt#1070]
### Extension version
5.9.1

### Short problem description
Map of location empty

### Steps to reproduce
1. add a new location
2. choose new location
3. show event with new location
https://www.schiedsamt.de/schiedspersonen/seminarangebot/details?tx_sfeventmgt_pievent%5Baction%5D=detail&tx_sfeventmgt_pievent%5Bcontroller%5D=Event&tx_sfeventmgt_pievent%5Bevent%5D=758&cHash=67188ae2cbea175508a5a7c7e9545d42

### Expected behaviour
Map should be displayed with location, as it does with events with old locations

### Actual behaviour
Map is empty (just the frame)

### Server configuration
**TYPO3 version:**
10.4.31

**PHP version:**
7.2.34

**Comment by derhansen** [comment]
The extension does not provide a map. Your map is a custom template implementation and has nothing to do with the extension nor is this a bug in the extension. Your page contains a JavaScript error, which most likely is related to the non working map. 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/2629896/213011805-6d89f84b-75ba-439d-ba83-7d7a7fc7176a.png">

Since your problem is not related to the extension but to a custom (most likely template) implementation, I'm closing the issue.
