### ISSUE TITLE
How to securely store reCaptcha public and private key 

### ISSUE THREAD

**Issue by SilentHunter124** [derhansen/sf_event_mgt#1104]
### Extension version
6.3.1

### Short problem description
When setting up recaptcha extension it has a global config in LocalConfiguration.php which works out of the box with for example a contact form. You simply place public and private recaptcha key in this php file without additional typoscript.

This extension explicitly wants to have those keys configured in typoscript and ignores the default behaviour.

### Expected behaviour
The extension should not get own public and private keys for recaptcha instead it should use ready extension reCaptcha with its corresponding configuration.

### Actual behaviour
You need to set typoscript: 

```
plugin.tx_sfeventmgt {
  settings {
    
    registration {
      captcha {
        enabled = 1
        type = reCaptcha
        reCaptcha.siteKey = ABC
         reCaptcha.secretKey = ABC
      }
    }
  }
}
```

### Question

I tried securely passing the values with getEnv(RECAP_PUB_KEY) but still no luck, is there another secure way ?

**Comment by derhansen** [comment]
See the documentation for the `getEnv` TypoScript function: https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/GetEnv.html

If you have an `.env` file, you may need to have a dot env connector installed to populate values from the .env file. 

Otherwise you can define environment variables e.g. on system level or in the `.htaccess` (apache only).

Example `.htaccess`:

```
RewriteEngine On
SetEnv RECAP_PUB_KEY "this is the public key"
```

Example TypoScript:

```
lib.recap_pub_key = TEXT
lib.recap_pub_key.value := getEnv(RECAP_PUB_KEY) 
```

This should work with any environment variable defined.

Since the recaptcha extension is not a dependency of ext:sf_event_mgt, I will not add any functionality to conditionally lookup configured API keys from that extension. 

I will however consider to move the setting for the API key to extension settings, so it can be defined in `LocalConfiguration.php` / `AdditionalConfiguration.php`.

**Comment by derhansen** [comment]
Follow up ticket: #1105
