### ISSUE TITLE
[FEATURE] Registration not available in saveRegistrationResultAction view 

### ISSUE THREAD

**Issue by r3h6** [derhansen/sf_event_mgt#1136]
### Extension version
6.4

### Short problem description
Registration object not available in saveRegistrationResultAction view 

### Expected behaviour
Registration object available in view

### Actual behaviour
Only event, messageKey  and titleKey available

### Server configuration
**TYPO3 version:** 11

**PHP version:** 8.1

**Comment by derhansen** [comment]
This is currently not implemented - basically because no one ever required it. I'm thinking of adding the registration uid as an additional parameter to the `saveRegistrationResultAction` and including the registration uid (either the real UID or `0` if no registration was created) as additional parameter to the hmac calculation.

This is however some kind of "breaking" change, since existing routing configuration will not fully work any more, as the additional registration uid parameter needs to be respected in routing. 

I will do some testing and evaluate, if it is possible/acceptable to add the parameter in a new minor version of the extension.

**Comment by r3h6** [comment]
Let me know if I can support you implement this feature

**Comment by derhansen** [comment]
Well, lesson learned with this one :-) Adding a new argument to an existing action will break hard, if the argument is expected through resolved routing. `saveRegistrationResultAction(int $result, int $eventuid, int $reguid, string $hmac)` will not work, if the `$reguid` argument is not configured in routing. TYPO3 will then fail with an exception, that the `saveRegistrationResultAction` expects 4 instead of 3 arguments, because `reguid` is not resolved. 

So in order to not be breaking, the new argument must be fetched inside the action code. There, request arguments are fully available (but not type safe).

**Comment by derhansen** [comment]
Will be included in 7.2.0 and 6.5.0
