### ISSUE TITLE
Payment webhooks are hard to implement

### ISSUE THREAD

**Issue by r3h6** [derhansen/sf_event_mgt#1139]
### Extension version
6.4.1

### Short problem description
Some payment providers suggest to use webhooks for processing the order after payment instead of relying the user gets really redirected to the success page. But when flag the registration as paid in a webhook before the user is redirect, the success page can not be displayed because of the "proceedWithAction" check

### Steps to reproduce
1.Implement payment according readme

### Expected behaviour
Some sort of configuration for disable the "if ($registration->getPaid())" check should be implemented.

### Actual behaviour
Error messsage "payment.messages.paymentAlreadyProcessed" is shown.

### Server configuration
11.5

7.4

**Comment by derhansen** [comment]
The `$registration->getPaid()` check is actually important in order to prevent re-processing of all payment-actions after the payment of a registration has been processed successfully. So a configuration flag to disable the check globally for all actions may lead to unwanted behavior (e.g. when `cancelAction` is somehow called after `successAction`). Also on websites with multiple payment providers, of which only one uses payment processing using webhooks, the check may be required in the `successAction`.

I think it will be better to add a PSR-14 event in `proceedWithAction`, where the check can be disabled based on the `$registration` and the `$actionName`. What do you think?

**Comment by r3h6** [comment]
I think a PSR-14 event would be a good solution

**Comment by derhansen** [comment]
Added a PSR-14 event, which now is available in version 6.5.0 and 7.2.0
