### ISSUE TITLE
Registration: The event record is not available anymore.

### ISSUE THREAD

**Issue by opaque01** [derhansen/sf_event_mgt#1141]
Hallo

TYPO3 Version: 11.5.19
Extension Version: 6.4.1
PHP 8.0.20

After click on the confirmation link the page opens with: "The event record is not available anymore."
But it is still available and also visible in List and Detail view.

thx opaque

**Comment by derhansen** [comment]
The whole registration process is covered with acceptance tests, so your problem is most likely result of a misconfiguration in custom templates (missing/wrong arguments for action) or wrong configured `checkPidOfEventRecord` setting in the plugin/TypoScript. Please check the templates included in the extension, where everything works as expected. 

Since this is no issue in the extension, I'm closing this issue now.

**Comment by opaque01** [comment]
> The whole registration process is covered with acceptance tests, so your problem is most likely result of a misconfiguration in custom templates (missing/wrong arguments for action) or wrong configured `checkPidOfEventRecord` setting in the plugin/TypoScript. Please check the templates included in the extension, where everything works as expected.
> 
> Since this is no issue in the extension, I'm closing this issue now.

I found the problem. I have to change the pluginName to "Pieventregistration" in my custom template files.
Thx opaque

**Comment by derhansen** [comment]
Yes, that actually documented here https://github.com/derhansen/sf_event_mgt/releases/tag/6.0.0

I think I will create a section in the documentation with breaking changes, so users doing major updates will better find information about required changes.
