### ISSUE TITLE
Disable overwrite demand always checked

### ISSUE THREAD

**Issue by r3h6** [derhansen/sf_event_mgt#1148]
### Extension version
7.2.0

### Short problem description
It is not possible to disable the "Disable overwrite demand" checkbox in plugin settings (flexform)

### Steps to reproduce
1. Add plugin
2. Uncheck "Disable overwrite demand" checkbox
3. Save

### Expected behaviour
Checkbox is not checked

### Actual behaviour
Checkbox is still checked

### Server configuration
**TYPO3 version:** 12.4

**PHP version:** 8.2

**Comment by derhansen** [comment]
Thanks for your report. This is "just" a visual bug. The value is actually unchecked, but since the default value of the FlexForm ist `1` and my DataHandler Hook unsets the whole field in FlexForm when empty, the default value is shown again if the FlexForm has not value.

Strange this worked in v11. I will check how to fix this
