### ISSUE TITLE
Fe_Group: Accessrestriction problem with Notification E-Mails

### ISSUE THREAD

**Issue by OliverPeh** [derhansen/sf_event_mgt#1155]
### Extension version
sf_event_mgt Version 6.5.1

### Short problem description
I have a problem with sending notification emails when I add user group rights to an event.
As long as I stay logged into the FE everything works correctly.  Login works - email notification is sent.
The link in the email also directs me correctly to the registration page (confirmRegistration).
If I open the email later and I am no longer logged into the VU, I get a problem because the event is then no longer accessible, because I then lack the user group rights.
I then get the following error as soon as the class sendUserMessage is called:

DERHANSEN\SfEventMgt\Service\NotificationService::sendUserMessage(): Argument #1 ($event) must be of type DERHANSEN\SfEventMgt\Domain\Model\Event, null given, called in /var/www/htdocs/hspv-2/docroot/typo3conf/ext/sf_event_mgt/Classes/Controller/EventController.php on line 707

Am I doing something wrong or do I have a thinking error?!

### Steps to reproduce
1. give event under Access a user group restriction, disable automatic confirmation.
2. log in to FE, event detail view
3. register for this event
4. log off in VU
5. use the confirmation link in the e-mail received.

### Expected behaviour
Since I already had the correct user group permissions for registering the event, these should not be checked again when sending the emails. 

### Actual behaviour
DERHANSEN\SfEventMgt\Service\NotificationService::sendUserMessage(): Argument #1 ($event) must be of type DERHANSEN\SfEventMgt\Domain\Model\Event, null given, called in /var/www/htdocs/hspv-2/docroot/typo3conf/ext/sf_event_mgt/Classes/Controller/EventController.php on line 707

### Server configuration
11.5.25

8.1.x

**Comment by derhansen** [comment]
Thanks for your report. If a TYPO3 record (in this case the event) if protected via fe_group access permissions, those permissions are always checked. TYPO3 will not "remember", if the access permissions have been verified during registration - the access permission check is always part of the TYPO3 persistence layer. 

So if you are not logged in and try to confirm to a registration for an access protected event, this will not work, since the lookup of the event will return `null`. It is mandatory to be logged in when confirming a registration to events that are access protected. 

The error is however not really nice and I will try to add a user friendly error message.

**Comment by derhansen** [comment]
I will not add any redirect for this special case, since this is too special and it can also have other reasons why an event is not found (e.g. event deleted). 

The correct way to create the confirmation links for events that are access protected is to always point links to the page, where ext:felogin is located and then append the confirmation link as `redirect_url` parameter (see ext:felogin docs for details). If the user is logged in, the redirect is automatically processed, if not, the user must login and is redirected to the confirmation page after successful login.

**Comment by derhansen** [comment]
Added a check which prevents the exception and shows a user readable error message instead. Will be included in version 7.3.2
