### ISSUE TITLE
Discussion: [FEATURE] Multiple tickets/prices for same event

### ISSUE THREAD

**Issue by sorenmalling** [derhansen/sf_event_mgt#1162]
### Extension version
 7.3.1 

### Short problem description
At current, a event can have a single price, with the possibility of setting a alternative price for a specific period of time.

I will like to open a discussion about, implementation of a event that can have multiple ticket types. 

 * Normal
 * VIP
 * Super-Expensive

Does this belong in a extension of the interface instead of a core feature?

I will be trying to implement it as a separate extension of the original package, to see if it's possible.

**Comment by derhansen** [comment]
I'm open for a discussion here, since I already used the extension to implement something similar (multiple price options including QR code based ticket system).

It is basically possible to use the extension without the need to enter a price in the `price` field of the event table. Instead, the Price Options Feature can be used (without price validity) to let the user select one of the available price options in frontend (registration must be extended here). 

I think, an options would be to extend the Price Options table with extra fields (e.g. title and description), so it is possible to use this as "ticket" prices in frontend. Adding another type of table (e.g. tickets) is not suitable I think, since the extension already has a lot of fields/tables.

One of the most important things is the price saved to the registration, when the user actually registers to the event. It must not be possible for a user to select price options not belonging to the event not price options not available (e.g. restricted by fe_groups access). Also it must be ensured, that the saved price will not change, if the value in the price options table changes. I usually handled this using one of the available PSR-14 events to ensure, that the actual selected price option value is valid and then saved the resulting price to the registration (new field). However, saving the price option is also required, so the event manager knows, which "ticket" has been bought.

So in term of requested "Ticket Types" I can add:

* `Price Option` field to registration
* `Price` field to registration
* Field `Title` and `Description` for price option
* Save price / price option price to registration field `price` in `saveRegistration()` action
* Save price option uid to registration field `price_option`
* Add potential new required PSR-14 events

Feel free to contact me on TYPO3 slack for further discussions.

**Comment by derhansen** [comment]
Im closing this issue now, since I never got feedback. Planing to extend the price options as described in #1185
