### ISSUE TITLE
Wrong sender for sending with smtp

### ISSUE THREAD

**Issue by matin73** [derhansen/sf_event_mgt#1166]
hello,

we have registration function activated with sending emails via smtp. but your extension sets user-email address as sender from instead of email address from settings. smtp needs email address from setting because hansi.huber@gmx.at is not allowed to be username for smtp sending mails

martin

**Comment by derhansen** [comment]
Thanks for your report. 

It is however not correct, that the extension sets the users email as sender address for emails. You must configure the sender global sender email address for all emails sent by the extension in TypoScript (see https://docs.typo3.org/p/derhansen/sf_event_mgt/7.3/en-us/ForAdministrators/Configuration/TsReference/Index.html#settings-notification-senderemail).

AFAICS the extension does at no point set the users email address as sender address.

**Comment by derhansen** [comment]
There is another setting, which you might check: https://docs.typo3.org/p/derhansen/sf_event_mgt/7.3/en-us/ForAdministrators/Configuration/TsReference/Index.html#settings-notification-registrationdataassenderforadminemails

If that setting is set to `1`, emails to the admin will be sent on behalf of the registering user (name and email address). Please check, if you have this setting active and if so, disable it. 

I'm closing this issue now, since in general there is not problem as described.
