### ISSUE TITLE
Outlook link checker cancels an event.

### ISSUE THREAD

**Issue by Konafets** [derhansen/sf_event_mgt#1179]
### Extension version
6.5.2

### Short problem description

If cancellation is allowed, the extension adds a cancellation link to the confirmation mail. When a user clicks it, he will redirected to the TYPO3 instance to cancel its participation. "Behind" the link is no button which a user has to click to cancel, instead the cancellation is happening by clicking the link. 

The issue occurs when a user uses Outlook and clicks the link. In this case Outlook performs a link check (for reasons I do not know) and activates the cancellation. When the user "arrives" at the page, a message informing the user that the event was not found or that his participation was already cancelled. 

### Expected behaviour

I think, the default template should contain a button which must be clicked to cancel.

### Server configuration
**TYPO3 version:** 11.5.32

**PHP version:** 8.1

**Comment by Konafets** [comment]
Thanks for the fast response. I will propose my solution to the customer and if approved implement it in a custom extension.

**Comment by derhansen** [comment]
6 months later and I now think different, since those spamfilters and link checkers are really getting annoing and lead to unwanted behavior (not only in sf_event_mgt, but also newsletter systems).

In case of sf_event_mgt (v7 only), I will add 2 new optional actions (see #1237), so user must double confirm/cancel the registration in a new view
