### ISSUE TITLE
Confirm new registration does not work

### ISSUE THREAD

**Issue by dennismetz** [derhansen/sf_event_mgt#1231]
### Extension version
Version 7.4.3 / TYPO3 12.4.14 / PHP 8.1.x

### Short problem description
Confirm new registration does not work. "This event is no longer available” is always displayed.

### Steps to reproduce
Create and register an event
“Activate automatic confirmation of event registration” is false
“Activate unique e-mail verification for registration” is also false. (if this is true, the registration page will no longer be found - or the page as soon as you click on “register” to take part)

The generated link in the mail looks like this:
/register/? tx_sfeventmgt_pievent[action]=confirmRegistration&tx_sfeventmgt_pievent[controller]=Event&tx_sfeventmgt_pievent[hmac]=e21c4f25631cb03bc11b2527df22688843af60ee&tx_sfeventmgt_pievent[reguid]=263&cHash=a8a7164cd131064d9c0ecc5e5a910f93

**Comment by derhansen** [comment]
Please read: https://github.com/derhansen/sf_event_mgt/releases/tag/6.0.0

Version 6.0.0 contains several breaking changes and all plugins have been renamed due to the switchableControllerActions deprecation. The link you posted uses the old `pievent` plugin, which has been removed in v6 of the extension. So please make sure to adapt all `f:link.action` ViewHelper usages in your templates as stated in the release notes.
