### ISSUE TITLE
Use DB type "decimal" instead of "double" to prevent not necessary db updates

### ISSUE THREAD

**Issue by websi** [derhansen/sf_event_mgt#1263]
### Extension version
Tell me which version of sf_event_mgt you use: 7.5.1

### Short problem description

On every save the price is written to db with MariaDb.

![sf_event_mgt](https://github.com/user-attachments/assets/16e3cc78-2895-40ff-a0fa-c1f3bc4c9cff)

### Steps to reproduce
1. Set an price without decimal places
2. Save record twice

### Expected behaviour
The price should not changed within history

### Actual behaviour
The price changed within history

### Server configuration
**TYPO3 version:** 12.4.19

**PHP version:** 8.1

**Comment by nourakhy** [comment]
install this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by derhansen** [comment]
Thanks for your report.

This problem will first be fixed in v8 of the extension, where DB fields are automatically created from the TCA schema. Changing to DB Type in `ext_tables.sql` to decimal will not work on all supported DB engines, since there seems to be a bug in PHPs pdo_sqlite implementation (https://bugs.php.net/bug.php?id=81397), which leads to rounding issues. TYPO3 v13 therefore has a workaround for this bug, which changes DB Type for affected fields for SQLite platform to string. 

See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81532/10/typo3/sysext/core/Classes/Database/Schema/DefaultTcaSchema.php

**Comment by derhansen** [comment]
Closing issue in favor to #1264
