### ISSUE TITLE
[FEATURE] Show events recursively in the Event Administration module

### ISSUE THREAD

**Issue by levemar** [derhansen/sf_event_mgt#1299]
### Extension version
7.6.0

### Short problem description
It would be interesting to be able to show events recursively in the Event Administration module. Our events are organized in different folders and some backend users would like to see them all at once. They already can do this in the List module
![image](https://github.com/user-attachments/assets/7538de55-f915-412c-91d9-85bccbd28826)
but they would love having this in the Event Administration module also.

### Server configuration
* TYPO3 version:12.4

**Comment by derhansen** [comment]
Thanks for your feature request. In generel, it should be possible to extend the backend module as suggested, although the free space for the filter options in the backend module is limited as I would like to avoid a line break. 

If the new option is used, it is important to evaluate, that the current user has access to each recursive evaluated page. If the user has no access permissions to a page in the resolved recursive pages, the page should not be included in the recursive pages, since we else have a information disclosure vulnerability.

**Comment by derhansen** [comment]
Feature has been added to v7 and v8 and will be included within the next release of the extension.
