### ISSUE TITLE
[Feature Request] Recurring events

### ISSUE THREAD

**Issue by Wintermilch** [derhansen/sf_event_mgt#1300]
This is a feature request for recurring events.
I didn't find a way in the docs to create recurring events and it would be really neat to have this feature.

It could work like this:
Add a checkbox to events for marking them as recurring. Then simply select a start date. 
Additionally a selection for a week day or day in a month (like first saturday) would be required.

**Comment by derhansen** [comment]
See https://docs.typo3.org/p/derhansen/sf_event_mgt/8.0/en-us/Faq/Index.html#recurring-events

Due to the described limitiation/complexity, this feature will not be added.

**Comment by derhansen** [comment]
Recurring events must either be created on block when saved in backend for the given recurrencees or calculated at runtime, which would make the extension really slow. But when it comes to registrations, you MUST have a unique record, where the registration is assigned to. Anything else will be uncomfortable in terms of usability (e.g. how should registrations for different recurrencees be shown in backend) and also in terms of maintainability of the extension. So basically, it would require a datahandler hook, which creates ALL recurrencees of an event, when an event record is created/changed in backend.

One other topic, that then will arise: You have an existing event with recurrencees and registrations to those recurrencees. Now the editor changes the recurring frequency and thereby a recurrency with existing registration drops out. How should the extension behave? Delete assigned registrations? Or have a process to "move" registrations to another recurrencee? Or have a hook, where a developer can implement own logic?

For sure, there are several other topics in terms of recurring events, which I did not mention or which users may expect to work.

All in all, this is not something I would like to maintain and since the extension is already pretty complex and I am the only one maintaining it, I will not add this feature or accept PRs for it.
