### ISSUE TITLE
[TASK] Test TYPO3 7.x compatibility

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#167]

**Comment by saneinsane** [comment]
**Problems I found (TYPO3 7.2):**

The backend module throws an error (unregistered argument).

Template Backend.html:
```
<f:be.container
		addCssFile="{f:uri.resource(path:'Css/administration.css')}"
```
change to:
```
<f:be.container
        includeCssFiles="{0: '{f:uri.resource(path:\'Css/administration.css\')}'}"
```

The datepickers in the backend module don’t work anymore (http://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.1/Breaking-62925-RemoveExtJsDateTimePicker.html)

**Comment by saneinsane** [comment]
For my another extension BE module I started with the sf_event_mgt-BE-Template. I switched to bootstrap markup for the table, made the shown fields configurable by TS and moved all filtering and sorting to JS (jquery DataTables); this worked pretty well for me.
Thank you for sharing your extension – fun to work with because it’s very well designed, documented and supported!

**Comment by derhansen** [comment]
Thanks for your feedback - it is really appreciated!

**Comment by derhansen** [comment]
Registration validation not working in TYPO3 7-master

**Comment by derhansen** [comment]
TYPO3 Core Bug has been fixed https://forge.typo3.org/issues/70017
