### ISSUE TITLE
action "icaldownload" is not allowed

### ISSUE THREAD

**Issue by derralf** [derhansen/sf_event_mgt#171]
Hi derhansen,

I upgraded to 1.0 and now get the following error:
```typo3 the action "icaldownload" (controller "event") is not allowed by this plugin```

I deleted cache in Backend and Install Tool, error is still there.
Any hints on how tolve this?

Thanks in advance,
Ralf

**Comment by derhansen** [comment]
Hello Ralf,

this is a known problem due to the change, that I had to add a new action to the switchableControllerActions.

I have written a note in the release notes https://github.com/derhansen/sf_event_mgt/releases, but maybe this is not completely clear.

You just have to open the plugin settings in the backend and reassign the "display mode" for the plugin.
This should solve your problem.

Let me know, if this works and I will add some release notes to the documentation section.

Best regards
Torben

**Comment by derralf** [comment]
OK, just didn't see this note.
Thanks
