### ISSUE TITLE
Combined view (list / detail / registration)

### ISSUE THREAD

**Issue by saneinsane** [derhansen/sf_event_mgt#176]
Add combined view as plugin setting to have all views on a single page.

**Comment by derhansen** [comment]
Do you mean, that you can have one page, that includes the plugin which can be used for both list, detail and registration? You do not mean multiple instances of the plugin on the same page?

**Comment by saneinsane** [comment]
Yes, I mean a single plugin for all views. Or is it possible to combine all three plugins on a single page (did not try yet)?

**Comment by Jpsy** [comment]
I just stepped into this issues as well.
So the answer is NO: It is currently not possible to combine a LIST and a DETAILS version of the plugin on the same page. If you do so it will work at first (LIST shows the list, DETAILS shows nothing as no detail-action is provided in the query string). As soon as you click an event in the LIST view, the page reloads with an action=detail parameter and the LIST incarnation throws an error because it does not know how to handle that action.
The action "detail" (controller "Event") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.

**Comment by Jpsy** [comment]
After some research there is a solution for the problem. Set this in TS-Setup:
plugin.tx_sfeventmgt.mvc.callDefaultActionIfActionCantBeResolved = 1

Found it here:
http://wiki.typo3.org/Exception/CMS/1313855175

That last link also contains strategies to solve to problem right within the extension, so no additional TS is needed. That would be recommendable.

BTW:
Thanks for providing this nice extension, Torben. :D

**Comment by derhansen** [comment]
Sorry, I wont have time for this feature.
