### ISSUE TITLE
CSV export fails for non-admin users

### ISSUE THREAD

**Issue by Jpsy** [derhansen/sf_event_mgt#219]
Non admin users trying to export registration CSV files get an error message in BE. 

If debugging is OFF this is a red "Oops" box with text "You are not allowed to access the given folder".

With debugging ON the debug trace below is shown.

I tried to step through the code and the problem seems to be that non-admin users are not granted read access to folder /fileadmin/_temp_/. Then I created a filemount for this folder with read access for editors, but it did not solve the problem. I do not understand enough details of the TYPO3 background mechanics to nail the problem further down. What I found is that all permission checkes are skipped for admin users which is why it works for them.

![image](https://cloud.githubusercontent.com/assets/1806058/8620831/7fa2acd8-2722-11e5-86dc-376618388de0.png)

**Comment by derhansen** [comment]
Thanks for your detailed report. 

Currently the CSV export always exports temporary files to the **fileadmin/_temp_/** folder, so a quick fix would be to enable write access for the backend user to this folder.

I will check if I can provide a configurable solution for this problem.

**Comment by Jpsy** [comment]
Yes, enabling write access to fileadmin/_temp_/ was exactly what I tried by creating a file mount for that path and give editors write access to it. But it did not work. 
From my debugging it seemed that TYPO3 checks the read request for the temporary file only against the (list of) "_processed_" folders and not against any file mounts. 
Is it possible that the access method call that you use for reading the temporary file is not suitable for files in file mounts?

**Comment by derhansen** [comment]
I debugged a little bit in my demo TYPO3 installation.

In order to allow non-admin users to export the CSV file, you must create a filemount to ```/fileadmin/_temp_``` and the user must have R/W access to the folder and must also be able to R/W files in that folder. With this setup, the CSV export runs fine.

By default, this folder should be used for import/export operations (at least if the documentation is still valid http://wiki.typo3.org/File_Abstraction_Layer#fileadmin.2F_temp_.2F)

I will add a check if the folder is accessible and the user is able to write files in the folder and also update the documentation about how to configure the CSV export for users not having full access to fileadmin.

**Comment by Jpsy** [comment]
Hmmm. I think I have done all that you had. File mount is created, r/w access to file mount is enabled for my BE users, OS file/folder permissions must be OK (otherwise admin users would have problems too). No idea what I overlooked. I will check again on Monday.

**Comment by derhansen** [comment]
Could you resolve the problem?

**Comment by Jpsy** [comment]
I tested on two systems (OSX and Win) and ... it works! :D
I have no idea what went wrong the first time I tried. 
Creating a file mount for _temp_ and giving the editors read/write permissions to it is the solution.
Thanks for checking and solving the puzzle!

**Comment by derhansen** [comment]
Thanks, I have updated the documentation regarding the file mount for the CSV export.
