### ISSUE TITLE
[FEATURE] Add support for recurring events

### ISSUE THREAD

**Issue by andinger** [derhansen/sf_event_mgt#354]
It would be very nice, if this extension gets support for recurring sometime. The user should be able to choose the interval of the recurrence (day, week, month, year). The event should occur with the calculated date until a given end date is reached. Additionally there should be the possibility to add exception dates where the event won't takes place.

**Comment by derhansen** [comment]
I'm afraid this feature will never make it into the extension, since recurring events will not smoothly work together with event registration. 

**Background:**
An event registration will need a unique event to be saved to, since a user would registering for a particular recurrence of the event. One way to archive this, would be to save each event recurrence as a database entry, so unique registration still will be possible. For daily recurring events, this would mean ~365 records per year and when the backend editors changes the recurrence frequency, a lot of DB updates would be needed. This is not very handy and makes the extension harder to understand and maintain.

I will add a FAQ article about this feature request and why I decided not to implement it.

**Comment by derhansen** [comment]
Added FAQ article
