### ISSUE TITLE
Possibility to add first name and last name at multiple registrations

### ISSUE THREAD

**Issue by AdlerBH99** [derhansen/sf_event_mgt#381]
If you register for example for 3 people it would be cool to have the possibility to add the name for each of them.

The use case are registrations for trainings. 

E.g. the HR manager or technical manager wants to send his employees to a training. He registers at the event module 3 or more people and now he wants to add the names of them.

On the other side our customer needs to know who will attend the training.

Thank you in advance!

**Comment by derhansen** [comment]
I created this feature in a customer project and decided not to add it to the main extension, since it requires breaking changes in the registration process.

An easy solution for you would be to add your own field to the registration process, where you ask for the participant names and add a validator, if the amount of registrations is > 1, so the field must be filled out.
