### ISSUE TITLE
Allow ical-download from list view

### ISSUE THREAD

**Issue by christian-fries** [derhansen/sf_event_mgt#400]
### Extension version
1.8.0

### Short problem description
When I add a link to the icalDownloadAction to the list template the download will not be called because the icalDownloadAction is not allowed by the switchableControllerActions for "What to display" => "List"

### Steps to reproduce
1. Add plugin with "What to display" => "List"
2. Add `<f:link.action action="icalDownload" arguments="{event : event}"><f:translate key="event.icalDownload" /></f:link.action>` to the template
3. Click on the link.

### Expected behaviour
iCal-File should be provided

### Actual behaviour
Page loads again with some query parameters

### Server configuration
**TYPO3 version:**
TYPO3 CMS 7.6.15
**PHP version:**
5.6.26

**Comment by derhansen** [comment]
Well, this is sad, since when I add an additional Action to the switchableControllerAction, then all Plugin settings using then old "List" setting must be reconfigured in every plugin. 

I have a solution for this problem. Please configure a page, where you add the Plugin to show event details. Then you can extend the iCalDownload action in the list view by adding the pageUid parameter as shown below

```
<f:link.action action="icalDownload" arguments="{event : event}" pageUid="{settings.detailPid}"><f:translate key="event.icalDownload" /></f:link.action>
```

**Comment by derhansen** [comment]
I add the solution to the FAQ section in the documentation section of the extension.
