### ISSUE TITLE
Document extending model without Ext:extender

### ISSUE THREAD

**Issue by tmotyl** [derhansen/sf_event_mgt#453]
### Extension version
development
### Short problem description
Documentation suggest using EXT:extender to add fields to the event model.
This approach is fine, unless you want to add a property which is a collection of objects (ObjectStorage).
Then you need to also add a  line in a object constructor for initializing the property.
And this will fail with EXT:extender, as it does not support merging of the class methods.

Alternatively one can easily extend Extbase model with plain extbase.
Just add following TS
```
config.tx_extbase {
    objects.DERHANSEN\SfEventMgt\Domain\Model\Event.className = Vendor\MyExt\Domain\Model\Event
    persistence.classes {
        Vendor\MyExt\Domain\Model\Event {
            mapping.tableName = tx_sfeventmgt_domain_model_event
        }
    }
}
```
and add properties you need to the new class  `Vendor\MyExt\Domain\Model\Event`. This class will be automatically used by extbase. The new class has to of course inherit from `DERHANSEN\SfEventMgt\Domain\Model\Event`.

**Comment by derhansen** [comment]
I have recently switched to suggest ext:extender, because of problems with Extbase extending of existing domain models when using PHP7, since e.g. a controller action then receives the extended domain model as argument and PHP7 will throw an error, that ExtendedClass is not compatible with ExpectedClass

The next version of ext:extender will contain merging of constructors (see https://github.com/evoWeb/extender/commit/4a942532ccb826eddd2123ed2aa25934cbc5c6d9), so object storage initialization will pe possible.

Does this help?

**Comment by tmotyl** [comment]
When extending model you should not change controller methods signature. So you will not get en error in PHP7.
However Extbase will deliver correct (Vendor\MyExt\Domain\Model\Event) class to the controller in the  approach I have proposed.
And as my apporach doesn't need a third party extension and is supported by the core out of the box since TYPO3 4.6 I like it more ;)

**Comment by derhansen** [comment]
Thanks, I updated the demo extension and the documentation
