### ISSUE TITLE
New input fields for registration form

### ISSUE THREAD

**Issue by fabianscholz** [derhansen/sf_event_mgt#461]
### Extension version
2.0.0

### Short problem description
I try to add new custom fields into the registration form. We need more fields for customer registration. The new fields must be validatable.

A simple add new fields into the fluidhtml and language.xml does not work unfortunately.
I get the following error:

`	
Oops, an error occurred!
Exception while property mapping at property path "": Property "position" was not found in target object of type "DERHANSEN\SfEventMgt\Domain\Model\Registration".
More information regarding this error might be available online.`

I could not find any documentation about that.

### Server configuration
**TYPO3 version:** 8.7.1
**PHP version:** 7.1

**Comment by fabianscholz** [comment]
https://github.com/derhansen/sf_event_mgt_extend_demo

**Comment by SilentHunter124** [comment]
Hi *,

first of all many thanks for this great extension and the high code quality. It is ideal for non profit organization to manage events.

Unfortunately I also have trouble with the problem mentioned above on our non profit organization site.

It is quite better to have some kind of configurable registration fields per event, because they are individually for every single event. For this use case it is not possible to build everytime an extension from scratch.

Do you have any plans to support attribute fields which can ne stored in the backend sysfolder as element and use them in the registration part of an event?

Would be a really great feature..

**Comment by derhansen** [comment]
@SilentHunter124 I have created a similar feature in a customer project, where the customer can add additional field per registration. Currently, the feature only covers Radio-Fields, but I think a more flexible solution can make it into the main sf_event_mgt extension some day. 

I have created a new issue for this feature request (see #467). I can't say, when this feature will make it to the main extension, since time is short at the moment.

**Comment by SilentHunter124** [comment]
No problem. It would make this extension extremely flexibel. Thank you for opening a feature request. I tried it myself by adding additional tables and connecting this models but my knowledge about extending existing things in typo3 framework are limited...
