### ISSUE TITLE
Error Message "Terms and Conditions" not translated

### ISSUE THREAD

**Issue by derralf** [derhansen/sf_event_mgt#549]
### Extension version
1.8.1

### Short problem description
Fehlermeldung "Terms and Conditions" nur auf englisch ("The given subject is not true.")

### Expected behaviour
Fehlermeldung "Terms and Conditions" sollte deutsch sein

### Actual behaviour
Fehlermeldung "Terms and Conditions" ist auf englisch ("The given subject is not true.")

### Server configuration
**TYPO3 version:**
6.2.11
**PHP version:**
5.6

**Comment by derhansen** [comment]
Sorry, but there is nothing I can do about this behavior, since the error message is hardcoded in TYPO3 Core 6.2 (see: https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_6-2/typo3/sysext/extbase/Classes/Validation/Validator/BooleanValidator.php#L66)

Since TYPO3 7.6, the message can be localized, so you could consider to update to TYPO3 7.6 or 8.7.

**Comment by derralf** [comment]
ok, thanks anyway
I now use this hacky solution in my Registration.html
instead of...
```
<f:render partial="FormErrors" arguments="{field: 'registration.accepttcOrAnyOtherCheckboxField'}"/`>
```
...I now use this (copied from your FormErrors.html-Partial)
```
<f:form.validationResults for="registration.accepttcOrAnyOtherCheckboxField">
    <f:if condition="{validationResults.flattenedErrors}">
         <div class="field-errors">
            <span class="error">Dies ist ein Pflichfeld.</span>
        </div>
    </f:if>
</f:form.validationResults>
```
as i only have one language this works for me (no translation / translation key needed here for me)
