### ISSUE TITLE
[FEATURE] How to add asterisk or hint that a field is required?

### ISSUE THREAD

**Issue by jwittorf** [derhansen/sf_event_mgt#550]
Hi,

I'm using 3.0.4 with TYPO3 7.6.*, I would like to show the users a hint which fields are required to improve the UX. I couldn't find an easy way like e.g. the old formhandler:

`<label class="control-label" for="###fieldname###">###LLL:###fieldname###### ###required_###fieldname######</label>`

Or maybe some other notation like:

```
<label class="control-label" for="title">
    <f:translate key="tx_sfeventmgt_domain_model_registration.title"/>
    <f:if condition='title.required' then='<em class="required">*</em>'></f:if>
</label>
```

Is there some kind of way I'm just not seeing or is something like this planned for further releases?

This is what I'm trying to achieve:

![image](https://user-images.githubusercontent.com/2085721/41723545-b652c1e2-756b-11e8-98c2-f714476b7186.png)

Thanks in advance!

**Comment by derhansen** [comment]
Currently, there is no easy way to show, if fields are required or not, since both built in fields can either be required (depending on TypoScript configuration) or additional registration fields can be required (depending on field configuration in registration record in BE).

I will create an additional ViewHelper for this feature in the upcoming version of the extension

**Comment by jwittorf** [comment]
Thanks for the info and adding this to the road map, I'll propose a second feature request, that would be nice to have in the future. Thanks for your efforts!
