### ISSUE TITLE
Allow tt_content elements in event description

### ISSUE THREAD

**Issue by jschrewe** [derhansen/sf_event_mgt#561]
The ability to add different content elements for the description of an event would be great. tt_news has that and it adds a very flexible way to add complex descriptions with images and logos.

I'd be willing to try to add that but I'd rather not maintain my own fork if that has no chance to get into the main project.

**Comment by derhansen** [comment]
In general this would be possible, but the feature will increase the level of complexity of the extension/codebase, which makes it harder for me to maintain. I suggest you create an extension for sf_event_mgt, which adds your required functionality without modifying the main project (see: https://github.com/derhansen/sf_event_mgt_extend_demo as an example)

You could copy required code for the relation to tt_content from ext:news (see: https://github.com/georgringer/news/blob/master/Configuration/TCA/tx_news_domain_model_news.php#L478 and https://github.com/georgringer/news/blob/master/Classes/Xclass/InlineRecordContainerForNews.php). There are for sure other parts, that are required in order to get things up and running link in ext:news, but I think this may be a good point to start from.

**Comment by derhansen** [comment]
Closing this ticket, since the feature will not be implemented.
