### ISSUE TITLE
Bad performance without feedback on event detail in BE

### ISSUE THREAD

**Issue by schrob3000** [derhansen/sf_event_mgt#592]
### Extension version
sf_event_mgt: 3.0.6

### Short problem description
Bad performance without feedback on events with many registrations (in backend).

### Steps to reproduce
Create an event with more than 200 registrations. If youre open the detail view, it takes a long time without user feedback.

### Expected behaviour
Some kind of user feedback (loading animation) if you are klick on an event with many registrations.

### Actual behaviour
You klick an event (many registrations). But you dont have any feedback what happens or if something happens.

### Server configuration
TYPO3: 8.7.19
PHP: 7.0.30

**Comment by derhansen** [comment]
Sadly there is nothing I can do in sf_event_mgt about this behavior, since it is related to TYPO3 Core.

You can review/test the pending TYPO3 Core Patch for this issue: https://forge.typo3.org/issues/82100

I really hope the patch will make it into V8 and V9 Core, since performance gain is really massive. Did not find any downsides until now.

**Comment by derhansen** [comment]
The patch has been merged, but will *not* get backported to TYPO3 v8
