### ISSUE TITLE
iCal Subscription

### ISSUE THREAD

**Issue by WiesBen** [derhansen/sf_event_mgt#636]
### Short problem description
Maybe this is already implemented I don't know. In the listview I would like to have an option to subscribe to ALL listed events as iCal (e.g. in outlook or mail app or iphone).

Is this already possible or a feature request?

**Comment by derhansen** [comment]
No, this is not possible currently. Best way to provide such a feature would be by an own ViewHelper, that accepts events from listAction as argument and returns iCal-File for all given events.

**Comment by WiesBen** [comment]
Thanks for your Feedback, but I think using ViewHelper wouldn't help, because iCal can use subscriptions to specific urls (e.g. outlook or an iphone just needs an url which is always the same). With this url it gets changes to events and so on, but when downloading it only once, it can not get updates, correct?

**Comment by derhansen** [comment]
Then an additional action would be required. Since this feature may only be useful for some extension users and because I want to keep the code as simple/clean as possible, I will not implement it to the main extension. Therefore I'm closing this issue. 

I suggest to create an own extension, which extends `sf_event_mgt` and adds a plugin, which renders the iCal for all selected events. 

Feel free to contact me, if you need help creating the required needs.

**Comment by derhansen** [comment]
Just found this for ext:news - https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/BestPractice/ICalendar/Index.html

Should work for sf_event_mgt as well. Maybe you give it a try.

**Comment by SilentHunter124** [comment]
Hi @derhansen ,

I am really sorry to pull this ticket back out. I can't get this work. Do you have a simple example how to do that with events?

Regards

**Comment by derhansen** [comment]
@SilentHunter124 See this updated link https://docs.typo3.org/p/georgringer/news/11.2/en-us/Tutorials/BestPractice/ICalendar/Index.html

I have no code ready for this, but if you follow/adapt the example from the news extension, this should be possible. I'm sorry I can not provide any further help on this - I never required this feature in any project so I have no code to share.
