### ISSUE TITLE
[FEATURE] Add possibility not to use the enddate in Backend

### ISSUE THREAD

**Issue by rnakielski** [derhansen/sf_event_mgt#653]
First of all: this is agreat and very useful extension!!
One thing is a little nasty for my client:
He does not want to use an end-date for his events. His events all last some hours (never days) and there is no defined end for his events. This is no problem in he frontend. I just do not use the end-date in the templates and everything is fine.
But in the backend an editor has to really care about the enddate not to be before or days after the end-date. Especially on changes this has been forgotten quite some times and this can make problems in the frontend (e.g. the event is not shown in the calendar view).
Is there a possibility to set the end-date automatically to the same date-time as the start-date (or maybe a second after)? Best for me would be that the editor does not even see the end-date field. I did not see any hook or signal slot for this.
Maybe you can give me an idea how to achieve this. thanks

**Comment by derhansen** [comment]
Thanks for your feedback. 

You're right, there is no hook or signal in sf_event_mgt to archive your needs, since the extension is not involved in saving data in the TYPO3 backend. This is done in TYPO3 core using the [DataHandler](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/DataHandling/DataHandler.php). 

The DataHandler contains a lot of hooks and I think the `processDatamap_preProcessFieldArray` might be the right to use in your case.

Hope this helps. If you need personal (non free) support to implement requirements or extend the extension, feel free to contact me by email.

**Comment by derhansen** [comment]
Note: I removed the "Invalid event configuration" message in #879, when the startdate equals he enddate.
