### ISSUE TITLE
CSV of users can not be exported by editor (permission problem)

### ISSUE THREAD

**Issue by angeloprevitali** [derhansen/sf_event_mgt#664]
It is the same thing as already decribed in a older issue here https://github.com/derhansen/sf_event_mgt/issues/219 that the editor can not export a CSV even if the editor gets access to the given folder.

I get the following error:
Fatal error: Uncaught TYPO3\CMS\Core\Resource\Exception\InsufficientFolderWritePermissionsException: You are not allowed to write to the target folder

TYPO3: 8.7.26
PHP: 7.2
EXT:sf_event_mgt version: 4.1.0

Can you fix that somehow?

Regards,
Angelo

**Comment by derhansen** [comment]
Currently not. If user does not have read/write access to the folder, no Export is possible. I will rewrite the CSV export, so it does not require access to the filesystem, but priority is currently low, since there is a working solution (r/w access to `_temp_` folder)

No time schedule for the mentioned change yet. Sponsoring is of course possible and may speed this up a bit ;-)

**Comment by angeloprevitali** [comment]
Thanks for your ultrafst answer Torben :)

could you just give me an example HOW to give r/w access to a editor? I don't get this to make it work..

Thanks for your help & feedback.

Regards,
Angelo

**Comment by derhansen** [comment]
If you did not set a special upload folder for your BE user group (see https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/stable/Faq/Index.html#why-is-the-csv-export-button-not-shown-in-the-backend-module), this should be `fileadmin/user_upload/_temp_/` or `fileadmin/_temp_/`.

**Comment by angeloprevitali** [comment]
That's what i tried and did not worked :(

Daes it needs bough or just one of this? In your writing it says "OR"...

![FAQ — sf_event_mgt 4 1 0 documentation](https://user-images.githubusercontent.com/17588253/59031612-74d90e80-8864-11e9-860d-27690b3f3a98.png)

**Comment by derhansen** [comment]
If you create an own filemount as shown on the screenshot below, it should work.

![image](https://user-images.githubusercontent.com/2629896/59049672-d01cf800-8888-11e9-8ed5-02dce49a24e1.png)

Since only TYPO3 Core functionality is used in the CSV Export to create the temporary file, there is not much I can do in this case. Please check R/W permissions of the file mount and on the filesystem (should be handled by FAL in TYPO3 Core, but better check, if the folder is writeable). Also note, that the TYPO3 temporary folder contains underscores `_temp_`. This folder is automatically created by TYPO3, so make sure your filemount points to the correct folder (see screenshot above)

**Comment by angeloprevitali** [comment]
Dear Torben
thanks for your feedback and detailed informations. I tried this and it works now like it should, yeah :)
Reagrds,
Angelo

**Comment by derhansen** [comment]
Glad I could help :-)
