### ISSUE TITLE
[BUG] Long events do not show in calendar

### ISSUE THREAD

**Issue by mattweb** [derhansen/sf_event_mgt#672]
### Extension version
4.1.1

### Short problem description
Events that begin or end outside of the month shown are not displayed, when startdate or enddate are outside of the current calendar view.

### Steps to reproduce
1. Create event with startdate 28-07-2019 and enddate 05-08-2019
2. View calendar of July or August

### Expected behaviour
There should be an entry for each day that is between startdate and enddate in the current view.

### Actual behaviour
The event is neither displayed in the July nor in the August view.

### Server configuration
**TYPO3 version: 9.5.8**

**PHP version: 7.2.14**

**Comment by derhansen** [comment]
@mattweb Thanks for you report. I can confirm the issue and pushed a patch to the development branch that fixes the problem. Root cause for the problem was, that the search for events was only limited to events which started and ended between a given date range (for the calendar view, the current month).

Would you mind to test the patch (although I added a functional test for the scenario)?

**Comment by mattweb** [comment]
@derhansen I successfully tested it in my project! Thank you very much for the quick fix!

**Comment by derhansen** [comment]
@mattweb Thanks for testing. I will release a new version on TER and packagist soon.
