### ISSUE TITLE
errorHandling

### ISSUE THREAD

**Issue by newsdesigner** [derhansen/sf_event_mgt#676]
Does the error handling still work correctly with version 9.5.9 and sf_event_mgt version 4.1.2?
I get the 404 page of Typo3 when opening an expired event.
I have tried several options (redirectToListView, pageNotFoundHandler, showStandaloneTemplate), there is always the same result.

PHP 7.2

**Comment by derhansen** [comment]
Thanks a lot for reporting the issue.

It depends on what you mean with "correctly" ;-)

I debugged through this and things have changed with routing in TYPO3 9.5. When a URL is called for an event, the page routes tries to determine the event record using the `PersistedAliasMapper` aspect. It no event records can be looked up (e.g. event is hidden, deleted or no slug for the given alias), the Error Handling configured in "sites" steps in. So here, the setting `plugin.tx_sfeventmgt.settings.event.errorHandling` has absolutely no effect.

In TYPO3 8.7 and before, ext:realurl tries beside other lookup-methods to determine the event record using an own table `tx_realurl_uniqalias`. The difference here is, that if the event could not be determined, the extbase action was still called but with no parameters (no event uid passed). Therefore one could use the configured error handling in `plugin.tx_sfeventmgt.settings.event.errorHandling`.

However, the setting `plugin.tx_sfeventmgt.settings.event.errorHandling` will still work in TYPO3 9.5, if the detail view is configured to show an event set by the plugin (not passed through GET parameters) or to show an event using a shortcut.

ext:news has the same behavior, since I adapted functionality from there. See also https://github.com/georgringer/news/issues/1018

I will update the documentation about this, since this behavior is confusing. Please do not close this issue.

**Comment by newsdesigner** [comment]
Solved with the standard error handling:
Site (Configuration) > Error Handling > Show Content from Page 

Thank you for your help.

**Comment by newsdesigner** [comment]
What is the best practice for cs_seo? tx_news generates clean URLs in sitemap.xml
How should I change these lines for cs_seo?

additionalGetParameters {
	tx_news_pi1.controller = News
	tx_news_pi1.action = detail
}

My current configuration:

plugin.tx_seo.config {
    xmlSitemap {
        sitemaps {
            events {
                provider = TYPO3\CMS\Seo\XmlSitemap\RecordsXmlSitemapDataProvider
                config {
                    table = tx_sfeventmgt_domain_model_event
                    additionalWhere =
                    sortField = sorting
                    lastModifiedField = tstamp
                    pid = xx /* PID of your storage for events records  */
                    recursive = 1
                    url {
                        pageId = xx /* details PID  */
                        fieldToParameterMap {
                            uid = tx_sfeventmgt_pievent[event]
                        }

                        useCacheHash = 1
                    }
                }
            }
        }
    }
}

Is there a solution for the index and follow settings. The details page shouldn't actually be displayed in the sitemap. If you exclude the detail page with "noindex", the events will no longer be listed in the search engine. With "index" the empty detail page is added to the sitemap. I can not find a description of the problem or a solution. Has nobody observed the problem until now?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
There's a typo in what you added to the docs: "error" instead of "errer"

**Comment by derhansen** [comment]
Thanks, fixed
