### ISSUE TITLE
[DOC] Add sitemap example for tx_seo 

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#677]
What is the best practice for cs_seo? tx_news generates clean URLs in sitemap.xml
How should I change these lines for cs_seo?

```
additionalGetParameters {
	tx_news_pi1.controller = News
	tx_news_pi1.action = detail
}
```
My current configuration:
```

plugin.tx_seo.config {
    xmlSitemap {
        sitemaps {
            events {
                provider = TYPO3\CMS\Seo\XmlSitemap\RecordsXmlSitemapDataProvider
                config {
                    table = tx_sfeventmgt_domain_model_event
                    additionalWhere =
                    sortField = sorting
                    lastModifiedField = tstamp
                    pid = xx /* PID of your storage for events records  */
                    recursive = 1
                    url {
                        pageId = xx /* details PID  */
                        fieldToParameterMap {
                            uid = tx_sfeventmgt_pievent[event]
                        }

                        useCacheHash = 1
                    }
                }
            }
        }
    }
}

```
Is there a solution for the index and follow settings. The details page shouldn't actually be displayed in the sitemap. If you exclude the detail page with "noindex", the events will no longer be listed in the search engine. With "index" the empty detail page is added to the sitemap. I can not find a description of the problem or a solution. Has nobody observed the problem until now?

_Originally posted by @newsdesigner in https://github.com/derhansen/sf_event_mgt/issues/676#issuecomment-529241131_

**Comment by medarob** [comment]
For the speaking URLs I use this and it works

```
additionalGetParameters {
    tx_sfeventmgt_pievent.controller = Event
    tx_sfeventmgt_pievent.action = detail
}
```

**But there is another issue:**
Right now, all active events are shown in the sitemap (no matter if the event was in the past or if it's a current/future event). If I manually deactivate the event, the event is not in the sitemap anymore. (Which is prefered because the website shows only current or future events.)
Is there an option to automatically deactivate the event as soon as it's in the past? Or is there an option to omit active events which are out-of-date (via the seo config)? Maybe I have to check for the date?

**Comment by medarob** [comment]
I think I got a solution for my problem.
With
```
additionalWhere = `tx_sfeventmgt_domain_model_event`.`enddate` > UNIX_TIMESTAMP()
```
I get only the current event links in the sitemap.

**Comment by derhansen** [comment]
Thanks a lot for your input. I added a section about this topic in the documentation.
