### ISSUE TITLE
Don't refresh the site by changing the month?

### ISSUE THREAD

**Issue by dangele** [derhansen/sf_event_mgt#687]
### Extension version
3.0.5 

### Short problem description
The link for the next month at the calender view is a "normal" link where the Site refresh.
Is there a way to update the view just via ajax or is this planned in the future?

Beste Regards,
Daniel

**Comment by derhansen** [comment]
Hi Daniel, 

thanks for your feedback.

It is not out of the box possible to browse the calendar view without reloading the page. 

I did not test it, but you could try to extend the Previous/Next Links (e.g. by adding a custom page type and by passing the content element UID to the link) and then add some TypoScript to let the custom page type output the plugin (resolved by the content element UID) only. In theory, this should give you the possibility to fetch the link using AJAX / JavaScript. 

It is not planned to add this feature, since it will increase the complexity of the extension and make it more hard for me to maintain.

Best regards
Torben
