### ISSUE TITLE
[BUG] Subregistration has wrong sys_language_uid

### ISSUE THREAD

**Issue by christophlehmann** [derhansen/sf_event_mgt#688]
### Extension version

4.1.2

### Short problem description

Subregistrations have wrong sys_language_uid

### Steps to reproduce
- Translate an event
- Register to event with >1 amount of persons

### Expected behaviour
subregistrations and main registration should have the same sys_language_uid.

In the list of "my events" (my registrations) i only see the main registration (wrong). When i switch to default language i see the main registration + sub registrations (okay)

### Actual behaviour
Main registration has fe language (okay), sub registration has default language (not okay)

### Server configuration

8.X

**Comment by christophlehmann** [comment]
`ObjectAccess::getGettableProperties($registration)` only returns properties which have a public getter method.

Do we really need sys_language_uid for registrations?

**Comment by derhansen** [comment]
Thanks a lot for your feedback.

I had in mind, that there were some problems disabling the language feature for the `registration` TCA, but could not remember what.

I now spent some time digging into the problem and did some testing with removing the language feature from `registration` and `registration_fieldvalue`. This seems to work quite well until now.

When still must remain is the workaround to update the event `uid` for registrations saved in a different language and also the additional getters `getRegistrations` and `getRegistrationsWaitlist` are still needed in order to show the amount of registrations in translated events.

I created a new issue (#690) and will continue testing.

**Comment by derhansen** [comment]
There seems to be some problems when the language is removed for registrations and registration field values (field values missing in email of non default language). Therefore I think a better approach would be to set the `sys_language_uid` to -1 for all registrations and registration field values (see #690)
