### ISSUE TITLE
Feature FE users to create new events

### ISSUE THREAD

**Issue by Tonyt8** [derhansen/sf_event_mgt#691]
Hi 

sf_event_mgt: 4.1.3
Typo3 9.5.11
Bootstrap package 11.0.0

Is it possible to add an extra feature to allow logged-in FE users to create new events?
If this can be made possible what would your costs be?

Many thanks in advance.
Regards,
Tony

**Comment by derhansen** [comment]
Hello Tony,

the costs depend on your needs ;-) What do you expect when you say that fe_users should be able to create events? Should the event description be editable with CKEditor? Should it be possible to upload files/images? Should it be possible to edit events afterwards and if yes, by who (the fe_user created, all users of a fe_group)? Should it be able to delete events? ...

I do not have plans to add this feature to the main extension, but for sure an extension for sf_event_mgt can be created which covers your needs. I'm closing this issue here. In order to receive a cost estimate, please send me an email to derhansen@gmail.com, where you describe the task more precise.

Thanks and all the best
Torben
