### ISSUE TITLE
Missing registration field values in mail from a multi-language website

### ISSUE THREAD

**Issue by SoraNoIseki** [derhansen/sf_event_mgt#706]
### Extension version
4.1.3

### Short problem description
I have created an event with "registration fields" in a multi-language website. After sending the registration form, I as admin would receive a mail. But there are no any registration field values in the mail, while using the form with a not default language. 

I think it is not by reason of the template file, because by using the same form with default language, the registration field values would be appeared in the mail. But with the other language they were missing.

I have checked all settings but no idea on the reason. Hopping I could get some help hier :D Thanks!

### Steps to reproduce
1. Create an event in a multi-language website.
2. Add some registration fields. Also switch to the other language, and fill up the translations.
3. Enable registration and send a registration. One Registration with default language and another with an other language.

### Expected behaviour
In both mails, the registration field values should be appeared to tell admin that the user filled up in the form.

### Actual behaviour
But they were missing in the mail from the not default language site.

### Server configuration
**TYPO3 version:**
8.7.28
**PHP version:**
7.2.27

**Comment by derhansen** [comment]
I can confirm this in TYPO3 8.7 as described. For TYPO3 9.5, this works as expected (due to core changes in language handling) and there is a planned issue #690, which will set the language of all Registrations and Registration-Fields to -1, wo avoid problems on multilingual websites with registrations and field values.

Since the planned change in #690 is considered breaking, it will not make it into a version of the Extension supporting TYPO3 8.7 (and also, because the official support for TYPO3 8.7 ends in april this year).

A quickfix would be, to add `protected $_languageUid = -1;` in the `Registration` and `FieldValue` domain model.

**Comment by SoraNoIseki** [comment]
It works! Thanks a lot! :D

**Comment by derhansen** [comment]
I created a new version with support for TYPO3 8.7 anyway. The `sys_language_uid = -1` solution is suboptimal and does not work as expected on TYPO3 9.5. The new version 4.2.1 of the extension resolves the problem both for TYPO3 8.7 and 9.5 (see 7a0416644f4e19aed3ac7a1cf18dcaf130a562ec)
