### ISSUE TITLE
RSS xml error first line empty

### ISSUE THREAD

**Issue by UNI49** [derhansen/sf_event_mgt#708]
### Extension version
4.2.0

### Short problem description
When I add the [rss-feeds-by-using-a-plugin](https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/stable/ForAdministrators/RssFeed/Index.html#rss-feeds-by-using-a-plugin) there is an empty first line, which raised an exception for RSS feed readers (and web browsers)

### Steps to reproduce
1. Just add [rss-feeds-by-using-a-plugin](https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/stable/ForAdministrators/RssFeed/Index.html#rss-feeds-by-using-a-plugin)
2. Go to the page

### Expected behaviour
Don't add first empty line, nor any empty lines

### Actual behaviour
It shows an empty first line

### Server configuration
**TYPO3 version:**
9.5.14

**PHP version:**
7.2

**Comment by derhansen** [comment]
Yes, this is a known / general problem when adding the RSS by plugin, because actually the content element is rendered. You may also notice, that the default `<div>` from the content element is rendered, so one could try to add a special Layout for just the output of plugins in Fluid Styled Content.

This is basically the same for ext:news. I did not find out a suitable / easy way to make this work in TYPO3 together with Fluid Styled Content, so I suggest to use the TypoScript solution.

**Comment by UNI49** [comment]
Seems fair, I definitely understand.

Maybe we should add this explanation in the documentation, just to be clear on it ?

Thanks for help, really appreciated.

**Comment by derhansen** [comment]
Yes, you are right. I updated the documentation section and recommend to use TS for RSS feeds.
