### ISSUE TITLE
[TASK] Show visual warning for notification misconfiguration

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#774]
When an event is set to notify the organisator, but no organisator is selected or the organisator has no email address, a warning could be shown to the backend user.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi Torben,

I think a warning is not enough. If organisator-notification is set, setting an organisator should be mandatory. Otherwise missing emails are very likely - unfortunately happened at our company already. Workaround now ís to set the field as required via TCA. Of course this means that an orga needs to be set for events without registration, too. But this is better than missing emails.

Just in case you manage to implement something failsafe, it should also also work if organisator-notification is set to true via typoscript, so whenever you create a new event, so it can't be saved if no organisator is set.

**Comment by derhansen** [comment]
I implemented the "show warning" solution only. Working with dynamic field validation depending on the "Notify Organisator"  setting is not trivial to implement (would require an additional FormDataProvider) and will also make the event editing more complicated (e.g. no way to disable setting "Notify Organisator", if no organisator is selected). Implementing it as a DataHandler hook is also not suitable, since the record is saved anyway. 

So for now there is only a warning shown when the user either edits or saves an event where the organisator setting is incomplete (no organisator or no email)

![image](https://user-images.githubusercontent.com/2629896/113568347-ae216780-9610-11eb-950d-facd44e16888.png)

I believe this is better than before and editors will more easily spot a potential misconfiguration of an event.
