### ISSUE TITLE
[FEATURE] Notification mails also for speakers

### ISSUE THREAD

**Issue by zolthan** [derhansen/sf_event_mgt#776]
### Extension version
Version 4.2.2 with Typo3 8.7.32

### Short problem description
We need to get our speakers notified by mail.

It would be perfect not only to be able to send the notification mails to organisators and admins, but also to the speakers. Could you add this feature in the future? Therefore the speakers also need an email address and the mail send process needs to be extended for the speakers.

**Comment by derhansen** [comment]
Version 4.x is in Security Updates and Bugfix mode, so I will not add any new features to this version.

For version 5.x this feature could be added.

**Comment by zolthan** [comment]
If it will be released for Typo3 10, it will be fine. Then I need to make the step towards Typo3 10... Maybe I can check your changes to implement them in 4.x

**Comment by derhansen** [comment]
After rethinking about the feature, I decided not to implement it, since I think it may not be used often (never had this requirement in a project since I created the extension) and the demand may come up quickly to limit emails sent to speakers to a certain type of notification only. Therefore I suggest to use one of the many PSR-14 events in the extension (e.g. `AfterAdminMessageSentEvent`) to send a notification to event speakers if required.
