### ISSUE TITLE
Edit registration

### ISSUE THREAD

**Issue by kaialt** [derhansen/sf_event_mgt#796]
Feature request: At the moment you can only cancel your registration. It would be nice, when you also can change/ edit the registration especially the "field_values". Is there a possibility do that?

**Comment by derhansen** [comment]
A simple "edit registration" link sent along with the registration email is IMO a no go, since everyone who has access to the link also has access to the data entered in the registration process. 

Due to data security reasons such a feature should only be available when the user is logged in to the TYPO3 website (fe_user login). This would require, that all users registering to events must have a fe_user account, so there is a relation between the user and the registration object.

I think, this use case is too special to implement it as part of the main extension. I suggest to create an additional extension which extends sf_event_mgt and implements the required needs. There is a demo extension available (https://github.com/derhansen/sf_event_mgt_extend_demo) which shows how the extend sf_event_mgt.

**Comment by kaialt** [comment]
Thanks a lot for your answer and the great work with this extension. 
Sorry, I was not clear enough: I need a "Edit-link" for loggedin fe_user who has already registerd to an event, so the can change their registration data like "field_values".

**Comment by derhansen** [comment]
The use case of this feature is too special IMO, so I decided to not implement it to the main extension.
