### ISSUE TITLE
Provide more information on event item level after successful registration

### ISSUE THREAD

**Issue by danielkoch** [derhansen/sf_event_mgt#812]
### Extension version
4.3.1

### Short problem description
I want to provide more information to registered users AFTER a successful registration.

Use case: Registration for online events. Additional information: dial-in data for each event.

### Expected behaviour
Some additional information are visible on event detail page if user is logged in AND she/he is successful registered for this event.

### Actual behaviour
All information from available event fields are visible for all non-registered visitors.

### Server configuration
**TYPO3 version:** 9.5.22

**Comment by derhansen** [comment]
The detail view is fully cached and showing individual user registration information on event basis with either only be possible, when the view is uncached or when there is an additional AJAX route where additional registration information can be fetched in the background. 

I implemented similar requirements in a customer project as part of an additional extension that extends sf_event_mgt. I suggest you to do the same, since I currently have no plans to add this feature (which always depends on customer requirements) to the main extension.

**Comment by derhansen** [comment]
Note: The user registration plugin will at some time get a detail view, where registered fe_users can view event details (see #555). This view will be uncached, but will also require an active fe_user session.

**Comment by danielkoch** [comment]
@derhansen: Thanks for your quick reply. I share your opinion not to include such functionality into the core. If possible it would be nice if you could share some code of your custom extension. Especially because this functionality will only work if you have a connected FE user, because otherwise you cannot check the permission. Same as for #555.

**Comment by derhansen** [comment]
Sorry, I can not share any code in this regard. I can only describe, what has been coded. I created an additional extension with AJAX routes to several actions (e.g. `eventRegistrationStatusAction`). When this action is called, it evaluates if the user is logged in and if so, it renders a fluid standalone view which is returned as part of the JSON response of the action. A JavaScript component in the frontend evaluates the JSON response and e.g. shows, if the user is registered or shows a custom "register now" button, which again calls an AJAX action where the user quickly can register to the event without even entering data. 

I will close this ticket for now and prioritize ticket #555
