### ISSUE TITLE
[FEATURE] Filter language navigation for untranslated events

### ISSUE THREAD

**Issue by christophlehmann** [derhansen/sf_event_mgt#817]
### Short problem description

My events detail page is translated, but for a non translated event, the language menu still contains a link to that language.

It could be done with menu processor, see https://github.com/georgringer/news/commit/99caedee249be76dcc1da4c7ad569ca12ba55a66

**Comment by medarob** [comment]
I just stumbled upon the same issue.
The language menu still contains the possibily to switch to another language, even if the event translation does not exist.

TYPO3 9.5.23 and Events 4.4

**Comment by derhansen** [comment]
@medarob I originally planned to backport this feature to sf_event_mgt 4.x, but since 4.x is compatible with TYPO3 8.7 and 9.5, the code from the merged pull request can not be adopted as easily as I have hoped. I therefore decided not to backport the feature to version 4.x 

If you need this feature for v4, I suggest you to add the code from b7f67c6 to a custom extension with own namespace.
