### ISSUE TITLE
[FEATURE] Allow scrolling in calendar not only with "next" and "previous"

### ISSUE THREAD

**Issue by rintisch** [derhansen/sf_event_mgt#854]
### User story
As a user I want to be able to select not only the next or previous month for scrolling through the calendar. A functionality as given in the backend would be a highend solution. But it would already be nice if the month could be chosen with a drop down? 

Not sure whether this is important enought to become a part of the extension...

**Comment by derhansen** [comment]
When you customize the calendar view for your website, you can use basic fluid function to create the required links as shown below.

```
<f:for each="{0:1, 1:2, 2:3, 3:4, 4:5, 5:6, 6:7, 7:8, 8:9, 9:10, 10:11, 11:12}" as="month">
    <f:link.action rel="nofollow" action="calendar" controller="Event" arguments="{overwriteDemand:{month: month, year: year}}">{month} {year}</f:link.action>
</f:for>
```

This will render links to january 2021 - december 2021 for the calendar. Of course, this is just an example and if basic fluid functions do not fulfill your requirements (e.g. you need always links to the next 12 month), I suggest you create an own viewHelper, which e.g. returns an array of month/year combinations that can be used to generate the links.

I have no plans to add this functionality to the default views of the extension, since e.g. a dropdown would require JavaScript (onChange event) and I believe that users will have individual requirements to such a functionality.

**Comment by rintisch** [comment]
Thank you for your feedback and the line of code. I will create a ViewHelper as solution.
Will close this issue now.
