### ISSUE TITLE
Custom notifications don't work since last update to 5.5.0

### ISSUE THREAD

**Issue by HenryAveMedi** [derhansen/sf_event_mgt#884]
### Extension version
sf_event_mgt 5.5.0

### Short problem description
<img width="610" alt="image" src="https://user-images.githubusercontent.com/51093175/123662849-207f9d80-d836-11eb-9a37-69bff7ecb2cb.png">

### Steps to reproduce
1. Go to event module and events pid
2. choose an event where participants are registered
3. Try to send a custom notification (error happens also with default included notification, as seen in screenshot)

### Expected behaviour
Send the e-mail chosen

### Actual behaviour
typo3 error

### Server configuration
**TYPO3 version:** 10.4.15

**PHP version:** 7.3.28

**Comment by derhansen** [comment]
There has been a breaking change in this area in version 5.1.0 of the extension in order to provide more flexibility when creating and sending custom notifications - see https://github.com/derhansen/sf_event_mgt/releases/tag/5.1.0

If you have overwritten the default templates for the backend module, you must ensure that the changes to `IndexNotify.html` template are applied as shown [here](https://github.com/derhansen/sf_event_mgt/commit/81f4ffd307d0f77b73e2076df43f53d45ae34e11#diff-5b22e7c6a50c242ceb78e1fe5951f089f6c0710eafe2ba746a48c4f9ad2d8c8c). Also if you extended something in the Controller, you need to make sure to migrate your code similar to the code in the mentioned commit.

**Comment by HenryAveMedi** [comment]
my bad, i thought i had deleted all templates related to mails. but it seems i missed some.
thank you, now that all of those are gone, it's working properly
