### ISSUE TITLE
[FEATURE] Use TCA Labels for field and values in export

### ISSUE THREAD

**Issue by christophlehmann** [derhansen/sf_event_mgt#888]
* I export the field `feUsers.address` and in the export file i see the column name "feUsers.address". I would be nice to have it localized to "Adresse".
* I export the field `feUsers.gender` and like to see it's value localized, Mann/Frau/Divers

Source for this localizations can be the TCA columns. In case of column values it may only be necessary for select/radio fields. 

What do you think?

**Comment by derhansen** [comment]
I currently have no idea how to implement such a feature without rewriting the whole export and for sure breaking existing implementations for users. Also registration fields may be tricky, if radio/check/select fields have different values than labels. 

Since the current solution is simple and also works when the extension is extended by custom fields, I would like to keep it as it is. 

In some customer projects I was asked to implement a custom export, which exports Excel files instead of CSV files. I achieved this by overwriting the whole exportAction and used `phpoffice/phpspreadsheet` to create a Excel file with all customer requirements in regards to data formatting. Maybe you can implement something similar for your project too.

**Comment by christophlehmann** [comment]
>Since the current solution is simple and also works when the extension is extended by custom fields, I would like to keep it as it is.

Okay, lets close it for now.

>I currently have no idea how to implement such a feature without rewriting the whole export and for sure breaking existing implementations for users. Also registration fields may be tricky, if radio/check/select fields have different values than labels.

Would could be tricky is to come from a property to the TCA config. Maybe it's possible. Will try to check it later.
