### ISSUE TITLE
[HoneyPot] GDPR and ReCaptcha

### ISSUE THREAD

**Issue by departement-maine-et-loire** [derhansen/sf_event_mgt#894]
Hello

For event registration, we can have spamchecking done by ReCaptcha, but it Google and it is not really GDPR compliant. To be compliant with GDPR, we should ask for consent and stuff.
Can we imagine doing this spamchecking with a more basic process? Something like hidden input, if it is empty registration is valid, if not no registration.

Is that a good idea/request for you?

Thanks for help.

**Comment by derhansen** [comment]
The next major version (TYPO3 11 only) of the extension will allow to use hCaptcha instead of recaptcha - see #886.

Did all check the other implemented spam - see https://docs.typo3.org/p/derhansen/sf_event_mgt/5.5/en-us/ForAdministrators/SpamPrevention/Spamcheck/Index.html

I think the [challenge/response](https://docs.typo3.org/p/derhansen/sf_event_mgt/5.5/en-us/ForAdministrators/SpamPrevention/Spamcheck/Index.html#the-challenge-response-spam-check) check is something that spambots may not easily pass

**Comment by derhansen** [comment]
I'm closing the issue now. In version 6.0 of the extension, it is possible to use hCaptcha and reCaptcha or all internal spam detection routines as mentioned in the docs
